version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: ../../GitHub/vacation-plan/nginx/Docker/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "82:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - db
    networks:
      - buzzvel_net

  # Container for Laravel
  app:
    build:
      context: .
      dockerfile: ../../GitHub/vacation-plan/PHP/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - "./:/var/www/html"
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=buzzveldb"
      - "DB_USERNAME=buzzvelroot"
      - "DB_PASSWORD=secret!132"
    command: bash -c "composer install && cp .env.example .env && php artisan key:generate && php artisan migrate && php artisan passport:keys && php-fpm"
    depends_on:
      - db
    networks:
      - buzzvel_net

  # Container for MariaDB
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3314:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: buzzveldb
      MYSQL_USER: buzzvelroot
      MYSQL_PASSWORD: secret!132
    command:
      [
        '--default-authentication-plugin=mysql_native_password',
        '--init-file=/docker-entrypoint-initdb.d/init.sql'
      ]
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - buzzvel_net

networks:
  buzzvel_net:
